language: python 

python: 
  - 3.5 

install: 
  - pip install mkdocs 

script: 
  - cd database 
  - mkdocs build 

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  
  keep-history: true
  on:
    branch: master